// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhoXji9YQxEup_9L3pV9Kex10Hdj6xTw',
    appId: '1:895445219165:web:585ccb5053901e2feb5ab4',
    messagingSenderId: '895445219165',
    projectId: 'skin-ntd',
    authDomain: 'skin-ntd.firebaseapp.com',
    storageBucket: 'skin-ntd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmX5Elc5dcgoEgar1Bs5Ld9oiA7bKeJO4',
    appId: '1:895445219165:android:bcada46e6f8c7c87eb5ab4',
    messagingSenderId: '895445219165',
    projectId: 'skin-ntd',
    storageBucket: 'skin-ntd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQHvXPf4L1UAtL4zg-2OtyXmRbkyMKpk',
    appId: '1:895445219165:ios:e45218db2d5a96f7eb5ab4',
    messagingSenderId: '895445219165',
    projectId: 'skin-ntd',
    storageBucket: 'skin-ntd.firebasestorage.app',
    iosBundleId: 'com.example.skinapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQHvXPf4L1UAtL4zg-2OtyXmRbkyMKpk',
    appId: '1:895445219165:ios:e45218db2d5a96f7eb5ab4',
    messagingSenderId: '895445219165',
    projectId: 'skin-ntd',
    storageBucket: 'skin-ntd.firebasestorage.app',
    iosBundleId: 'com.example.skinapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFhoXji9YQxEup_9L3pV9Kex10Hdj6xTw',
    appId: '1:895445219165:web:69af0b231abd885beb5ab4',
    messagingSenderId: '895445219165',
    projectId: 'skin-ntd',
    authDomain: 'skin-ntd.firebaseapp.com',
    storageBucket: 'skin-ntd.firebasestorage.app',
  );

}